POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbHZhcm9iIiwiaWQiOiI2MWQzNmE4NDhhMTY1YTY4Mzc3OGYxYmQiLCJpYXQiOjE2NDEzMjI3NDZ9.uhx-pYtrLSMyOj59KLVp9LdPXMC1fNAifhHh6BToxTo

{
    "title": "funblog",
    "author": "funwriter",
    "url": "fun.com",
    "likes": 7
}