POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbHZ1bGkiLCJpZCI6IjYxZDVkNDBhMzY3NmVlMzcxNmQ5MzFlNyIsImlhdCI6MTY0MTQwMzQyOX0.xkIu--myZRIeSFLNVGZQYb-IOhHzxayyzRZUEEJyns8

{
    "title": "fun blog",
    "author": "fun author",
    "url": "fun.com",
    "likes": 10
}