POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbHZ1bGkiLCJpZCI6IjYxZDVkNDBhMzY3NmVlMzcxNmQ5MzFlNyIsImlhdCI6MTY0MTg0MTA3OX0.yGSxj6KtAGVts0-D-LCidIIW2CujVAmpCnjv8UI6RUM

{
    "title": "dumb blog",
    "author": "dumb author",
    "url": "dumb.com",
    "likes": 11
}